### ISSUE TITLE
Supported Protocols?

### ISSUE THREAD

**Issue by DeadSuperHero** [thefederationinfo/federation-tests#13]
I think this is a great initiative, and I'm super happy to see projects already using it!

I'm curious, though: what protocols does this test suite currently support? Can only projects use it for the Diaspora federation protocol, or can other protocols be used as well?

I ask because I think this could be a super useful tool for testing cross-platform federation, and would be interested in seeing whether supporting OStatus and ActivityPub networks would also make sense here.

**Comment by Zauberstuhl** [comment]
Well actually that is kind of the wrong question. Your question should be "what projects are supported".
Right now, I implemented following projects:

* Diaspora
* GangGo
* Socialhome
* Mastodon

Since none of the mentioned projects uses ActivityPub AND the Diaspora protocol there are no tests for a cross-protocol yet. But that should change for at least GangGo soon. I am already working on a ActivityPub implementation :beer:

> Can only projects use it for the Diaspora federation protocol, or can other protocols be used as well?

As long as the project fits into a Docker container we can write tests for it :)

Does that answer your question?
